// GENERADO por scripts/build-video.mjs — no editar a mano.
export const FPS = 30;

export type Shot = {
  clipSrc: string;
  durationInSeconds: number;
  startFromSeconds?: number;
  kenBurns?: "in" | "out" | "none";
  framed?: boolean;
  isImage?: boolean;
  sfx?: boolean;
};

export type Overlay =
  | { kind: "caption"; text: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "stat"; value: string; sub: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "hook"; text: string; fromSeconds: number; durationInSeconds: number };

export type Pin =
  | { kind: "image"; src: string; label?: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "duo"; srcA: string; srcB: string; labelA: string; labelB: string; fromSeconds: number; durationInSeconds: number };

export type VideoConfig = {
  width: number; height: number; fps: number;
  narrationSrc?: string; musicSrc?: string; totalDurationInSeconds: number;
  shots: Shot[]; overlays: Overlay[]; pins: Pin[];
};

// Tipos antiguos (compatibilidad; sin uso)
export type DataGraphic =
  | { kind: "percent"; value: number; label: string }
  | { kind: "counter"; value: number; label: string; prefix?: string; suffix?: string }
  | { kind: "bars"; label: string; items: { name: string; value: number }[] };
export type Scene = {
  id: string; durationInSeconds: number; type: "clip" | "data";
  clipSrc?: string; caption?: string;
  colorGrade?: "teal-orange" | "desaturated-cold" | "warm-neutral" | "none";
  kenBurns?: "in" | "out" | "in-out" | "none";
  data?: DataGraphic;
  transitionIn?: "slide-glitch" | "whoosh" | "shutter" | "none";
};

export const videoConfig: VideoConfig = {
  width: 1920,
  height: 1080,
  fps: FPS,
  narrationSrc: "assets/audio/narration.mp3",
  musicSrc: "assets/audio/musica-fondo.mp3",
  totalDurationInSeconds: 901.07,
  shots: [
  { clipSrc: "assets/clips/v-9737916.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7154235.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7154214.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-34448142.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7154208.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-30777154.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7154229.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7154230.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-3006972.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-1482055.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-6571483.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-11794068.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7875596.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-39041918.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8562464.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11901734.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38452040.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12839875.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38517980.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35018126.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38278795.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31177922.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30820452.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38046338.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5418966.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38403669.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36093115.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15075563.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34691446.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8104919.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-2075171.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1116131.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30288951.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18911703.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16685623.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30283097.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-17193158.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7361497.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33129175.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8469674.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987009.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11554487.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514802.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987010.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986876.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4482073.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987200.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7541835.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220643.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30075961.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987066.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-39112150.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693181.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693196.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220517.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4823761.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986475.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329380.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329376.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329385.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11330940.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6817054.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32024439.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13802590.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35186766.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4254005.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12769423.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11330934.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32084013.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11330933.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18495959.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4565729.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-2072827.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-37505403.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3006961.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11269279.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3066425.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11330915.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9790002.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9789997.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693197.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693178.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329403.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36381466.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4488721.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30010009.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4118546.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30283091.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4822919.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8104917.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5921059.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35666229.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33745418.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13802599.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33810551.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9737950.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986474.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1116141.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30391336.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4101734.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-37465966.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7844211.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7844215.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18101985.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6685052.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20156190.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7564889.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7541840.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7541845.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6685022.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7541837.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986481.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6870339.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6450803.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34477578.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32305292.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4468754.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30283093.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32305282.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30283098.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32305285.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220616.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220595.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220541.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157911.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329388.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220667.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28044004.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30062913.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157910.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32024438.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31802320.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3936776.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4707185.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157908.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5911023.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220606.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-10566891.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6158070.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13643097.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6636563.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11330932.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3757013.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5998863.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3134599.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157907.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3002365.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4281149.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157909.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8262625.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6872084.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9519134.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5309353.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11742625.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29554928.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15775322.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7647563.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7577931.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8471048.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8293493.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154212.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6817063.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6817057.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154224.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987018.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987024.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986482.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8470382.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986484.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514835.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986479.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987028.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28928755.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29780004.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-2053420.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35599597.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4317422.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36223712.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7378097.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33666250.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38854050.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13371634.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30627892.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34118771.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3059072.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14228182.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14228180.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-26542243.mp4", durationInSeconds: 4.07, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false }
  ],
  overlays: [
  { kind: "hook", text: "COCHES QUE NUNCA\nDEBES COMPRAR", fromSeconds: 3.94, durationInSeconds: 2.6 },
  { kind: "caption", text: "REPARACIONES QUE CUESTAN MÁS QUE EL COCHE", fromSeconds: 26.23, durationInSeconds: 2.5 },
  { kind: "hook", text: "AUDI Q7 (2ª GEN)\n2019-2024", fromSeconds: 49.18, durationInSeconds: 2.6 },
  { kind: "stat", value: "SUSPENSIÓN NEUMÁTICA", sub: "FUGAS + COMPRESOR QUEMADO", fromSeconds: 69.42, durationInSeconds: 2.8 },
  { kind: "caption", text: "SÍNTOMA: APARCADO, SE INCLINA HACIA UN LADO", fromSeconds: 94.44, durationInSeconds: 2.5 },
  { kind: "stat", value: "4 CIFRAS", sub: "RENOVAR EL SISTEMA NEUMÁTICO", fromSeconds: 121.64, durationInSeconds: 2.8 },
  { kind: "hook", text: "FORD FOCUS (4ª GEN)\n2019-2021", fromSeconds: 135.22, durationInSeconds: 2.6 },
  { kind: "stat", value: "FUGA DE ACEITE", sub: "EN LA CAJA (MANUAL Y AUTOMÁTICA)", fromSeconds: 155.54, durationInSeconds: 2.8 },
  { kind: "caption", text: "SIN ACEITE = CAJA DE CAMBIOS DESTROZADA", fromSeconds: 188.04, durationInSeconds: 2.5 },
  { kind: "hook", text: "JAGUAR E-PACE · DISCOVERY\nSPORT · EVOQUE (2019-24)", fromSeconds: 208.04, durationInSeconds: 2.6 },
  { kind: "stat", value: "MOTOR INGENIUM", sub: "ACEITE + CALOR + CADENA", fromSeconds: 230.64, durationInSeconds: 2.8 },
  { kind: "caption", text: "LO MÁS GRAVE: CADENA DE DISTRIBUCIÓN", fromSeconds: 250.14, durationInSeconds: 2.5 },
  { kind: "stat", value: "OCU 64/100", sub: "LAND ROVER · ÚLTIMO PUESTO", fromSeconds: 265.39, durationInSeconds: 2.8 },
  { kind: "hook", text: "NISSAN QASHQAI (3ª GEN)\n2021-2022", fromSeconds: 285.3, durationInSeconds: 2.6 },
  { kind: "stat", value: "ELECTRÓNICA", sub: "PANTALLAS QUE SE BLOQUEAN Y REINICIAN", fromSeconds: 309.04, durationInSeconds: 2.8 },
  { kind: "caption", text: "SOLO 1ª SERIES · COMPRUEBA EL SOFTWARE AL DÍA", fromSeconds: 351.94, durationInSeconds: 2.5 },
  { kind: "hook", text: "RENAULT CLIO V · CAPTUR II\nE-TECH (2020-2022)", fromSeconds: 360.86, durationInSeconds: 2.6 },
  { kind: "stat", value: "+334.000", sub: "COCHES EN LA CAMPAÑA DE RENAULT", fromSeconds: 387.56, durationInSeconds: 2.8 },
  { kind: "caption", text: "FUGA EN LA JUNTA DE LUBRICACIÓN DE LA CAJA", fromSeconds: 406.91, durationInSeconds: 2.5 },
  { kind: "caption", text: "EXIGE QUE HAYA PASADO LA CAMPAÑA RENAULT", fromSeconds: 444.61, durationInSeconds: 2.5 },
  { kind: "hook", text: "STELLANTIS (CITROËN·FIAT·\nPEUGEOT·OPEL) 2019-24", fromSeconds: 451.51, durationInSeconds: 2.6 },
  { kind: "stat", value: "1.2 PureTech", sub: "CORREA DE DISTRIBUCIÓN EN ACEITE", fromSeconds: 467.97, durationInSeconds: 2.8 },
  { kind: "caption", text: "EL FALLO MECÁNICO MÁS EXTENDIDO DE EUROPA", fromSeconds: 496.67, durationInSeconds: 2.5 },
  { kind: "stat", value: "BlueHDi + AdBlue", sub: "SENSORES · CRISTALIZACIÓN · ARRANQUE BLOQUEADO", fromSeconds: 500.94, durationInSeconds: 2.8 },
  { kind: "hook", text: "TESLA MODEL 3\n(FREMONT 2019-2022)", fromSeconds: 541.42, durationInSeconds: 2.6 },
  { kind: "stat", value: "CALIDAD DE FABRICACIÓN", sub: "PANELES · MOLDURAS · SELLADO · PINTURA", fromSeconds: 565.61, durationInSeconds: 2.8 },
  { kind: "caption", text: "LAS DE BERLÍN (EUROPA) VAN MEJOR", fromSeconds: 603.29, durationInSeconds: 2.5 },
  { kind: "hook", text: "GRUPO VW (AUDI·SEAT·VW)\nSOFTWARE + CAJA DSG", fromSeconds: 617.86, durationInSeconds: 2.6 },
  { kind: "stat", value: "MQB EVO", sub: "SOFTWARE + INFOTAINMENT (2020-2022)", fromSeconds: 628.64, durationInSeconds: 2.8 },
  { kind: "caption", text: "GOLF 8: TANTAS QUEJAS QUE VOLVIERON LOS BOTONES", fromSeconds: 646.72, durationInSeconds: 2.5 },
  { kind: "stat", value: "CAJA DSG", sub: "MECATRÓNICA CARA · ACEITE OBLIGATORIO", fromSeconds: 658.64, durationInSeconds: 2.8 },
  { kind: "hook", text: "VOLVO XC60 (2ª GEN)\nSENSUS 2019-2022", fromSeconds: 692.95, durationInSeconds: 2.6 },
  { kind: "stat", value: "SISTEMA SENSUS", sub: "SE CUELGA · LENTO · SE REINICIA", fromSeconds: 714.24, durationInSeconds: 2.8 },
  { kind: "caption", text: "LOS POSTERIORES (ANDROID) VAN MEJOR", fromSeconds: 737.55, durationInSeconds: 2.5 },
  { kind: "hook", text: "EL PATRÓN:\nCOMPLEJIDAD + PRIMERAS SERIES", fromSeconds: 745.24, durationInSeconds: 2.6 },
  { kind: "caption", text: "CASI TODO: FALLOS DE LAS PRIMERAS SERIES", fromSeconds: 774.64, durationInSeconds: 2.5 },
  { kind: "hook", text: "LA LECCIÓN:\nNUNCA LA PRIMERA HORNADA", fromSeconds: 799.74, durationInSeconds: 2.6 },
  { kind: "caption", text: "ESPERA 2-3 AÑOS: COMPRA LA VERSIÓN DEPURADA", fromSeconds: 831.34, durationInSeconds: 2.5 },
  { kind: "hook", text: "SUSCRÍBETE", fromSeconds: 895.84, durationInSeconds: 2.6 }
  ],
  pins: [
  { kind: "image", src: "assets/img/img-audi-q7-2020.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 49.18, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-1.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 56.35, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-2.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 63.52, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-3.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 70.69, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-4.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 77.86, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 85.03, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-1.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 92.2, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-2.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 99.37, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-3.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 106.54, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-4.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 113.71, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 120.88, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-audi-q7-2020-1.jpg", label: "AUDI Q7 · 2019-2024", fromSeconds: 128.05, durationInSeconds: 7.17 },
  { kind: "image", src: "assets/img/img-ford-focus-2020.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 135.22, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-1.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 142.5, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-2.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 149.78, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-3.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 157.06, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-4.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 164.35, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 171.63, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-1.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 178.91, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-2.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 186.2, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-3.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 193.48, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-ford-focus-2020-4.jpg", label: "FORD FOCUS · 2019-2021", fromSeconds: 200.76, durationInSeconds: 7.28 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 208.04, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-1.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 215.07, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-2.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 222.09, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-3.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 229.11, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-4.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 236.14, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 243.16, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-1.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 250.19, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-2.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 257.21, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-3.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 264.23, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020-4.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 271.26, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2020.jpg", label: "E-PACE · DISCOVERY SPORT · EVOQUE", fromSeconds: 278.28, durationInSeconds: 7.02 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 285.3, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-1.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 292.17, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-2.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 299.04, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-3.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 305.91, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-4.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 312.78, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 319.65, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-1.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 326.51, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-2.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 333.38, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-3.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 340.25, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022-4.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 347.12, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2022.jpg", label: "NISSAN QASHQAI · 2021-2022", fromSeconds: 353.99, durationInSeconds: 6.87 },
  { kind: "image", src: "assets/img/img-renault-captur-2021.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 360.86, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-1.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 367.83, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-2.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 374.8, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-3.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 381.78, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-4.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 388.75, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 395.72, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-1.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 402.7, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-2.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 409.67, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-3.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 416.64, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-4.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 423.62, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 430.59, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-1.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 437.56, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-renault-captur-2021-2.jpg", label: "RENAULT CLIO V / CAPTUR E-TECH", fromSeconds: 444.54, durationInSeconds: 6.97 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 451.51, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-1.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 458.43, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-2.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 465.34, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-3.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 472.26, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-4.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 479.18, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 486.09, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-1.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 493.01, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-2.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 499.93, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-3.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 506.84, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-4.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 513.76, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 520.67, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-1.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 527.59, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2021-2.jpg", label: "STELLANTIS · PureTech / BlueHDi", fromSeconds: 534.51, durationInSeconds: 6.92 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 541.42, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-1.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 548.37, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-2.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 555.32, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-3.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 562.27, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-4.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 569.22, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 576.17, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-1.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 583.11, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-2.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 590.06, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-3.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 597.01, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021-4.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 603.96, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-tesla-model-3-2021.jpg", label: "TESLA MODEL 3 · 2019-2022", fromSeconds: 610.91, durationInSeconds: 6.95 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 617.86, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-1.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 624.68, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-2.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 631.51, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-3.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 638.34, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-4.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 645.16, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 651.99, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-1.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 658.81, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-2.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 665.64, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-3.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 672.47, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021-4.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 679.29, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volkswagen-golf-8-2021.jpg", label: "GRUPO VW · GOLF 8 / DSG", fromSeconds: 686.12, durationInSeconds: 6.83 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 692.95, durationInSeconds: 7.47 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021-1.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 700.42, durationInSeconds: 7.47 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021-2.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 707.89, durationInSeconds: 7.47 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021-3.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 715.36, durationInSeconds: 7.47 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021-4.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 722.83, durationInSeconds: 7.47 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 730.3, durationInSeconds: 7.47 },
  { kind: "image", src: "assets/img/img-volvo-xc60-2021-1.jpg", label: "VOLVO XC60 · SENSUS", fromSeconds: 737.77, durationInSeconds: 7.47 }
  ],
};
