// GENERADO por scripts/build-video.mjs — no editar a mano.
export const FPS = 30;

export type Shot = {
  clipSrc: string;
  durationInSeconds: number;
  startFromSeconds?: number;
  kenBurns?: "in" | "out" | "none";
  framed?: boolean;
  isImage?: boolean;
  sfx?: boolean;
};

export type Overlay =
  | { kind: "caption"; text: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "stat"; value: string; sub: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "hook"; text: string; fromSeconds: number; durationInSeconds: number };

export type Pin =
  | { kind: "image"; src: string; label?: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "duo"; srcA: string; srcB: string; labelA: string; labelB: string; fromSeconds: number; durationInSeconds: number };

export type VideoConfig = {
  width: number; height: number; fps: number;
  narrationSrc?: string; musicSrc?: string; totalDurationInSeconds: number;
  shots: Shot[]; overlays: Overlay[]; pins: Pin[];
};

// Tipos antiguos (compatibilidad; sin uso)
export type DataGraphic =
  | { kind: "percent"; value: number; label: string }
  | { kind: "counter"; value: number; label: string; prefix?: string; suffix?: string }
  | { kind: "bars"; label: string; items: { name: string; value: number }[] };
export type Scene = {
  id: string; durationInSeconds: number; type: "clip" | "data";
  clipSrc?: string; caption?: string;
  colorGrade?: "teal-orange" | "desaturated-cold" | "warm-neutral" | "none";
  kenBurns?: "in" | "out" | "in-out" | "none";
  data?: DataGraphic;
  transitionIn?: "slide-glitch" | "whoosh" | "shutter" | "none";
};

export const videoConfig: VideoConfig = {
  width: 1920,
  height: 1080,
  fps: FPS,
  narrationSrc: "assets/audio/narration.mp3",
  musicSrc: "assets/audio/musica-fondo.mp3",
  totalDurationInSeconds: 842.92,
  shots: [
  { clipSrc: "assets/clips/v-4822919.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-30288951.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-30283097.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-1116131.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-8104919.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-32083964.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-2075171.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-4707185.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-35018126.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-31220566.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-6157907.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-18911703.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-16685623.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-34593373.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157908.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7361497.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514802.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6870339.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987271.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987010.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514800.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986474.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8469665.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31802320.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11554487.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28197087.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986481.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4118546.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33129175.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514790.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986894.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3936776.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4488721.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30283091.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1183118.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35661056.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33870954.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32305278.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12471033.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32067533.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30283092.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986885.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986876.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4725892.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220643.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-39112150.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986879.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986893.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987276.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157913.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220655.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-17193158.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16304650.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7013918.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8104917.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30010009.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693197.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220571.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29498821.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6872084.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157910.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5309435.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4161528.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4281280.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13850345.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30752440.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9174926.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6312479.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36079508.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3752531.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16431350.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12769430.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693188.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693201.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986480.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4489804.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33129049.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7564885.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-19827952.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514793.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7844143.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7541932.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7019384.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7564888.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14132505.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7568443.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15556121.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8470704.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6685051.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7541925.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329418.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38148207.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28928755.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31196470.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5921059.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34224132.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31901299.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32031047.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31196474.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18337374.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-26929404.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8171135.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1315986.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-27365322.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34696869.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35183993.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13366968.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28795448.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987078.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18101989.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986890.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986881.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986482.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6870334.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987273.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986479.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986485.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693199.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329382.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693191.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514403.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33129205.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987026.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4223775.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-17770564.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12680273.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3913495.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13643097.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9174928.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6331328.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11330934.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35666229.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8630309.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34539090.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13967042.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20589891.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13802596.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15330792.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15775322.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-10566891.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987015.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987200.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514414.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514417.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20639318.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986476.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514398.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7006123.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8470302.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987066.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14514835.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35849341.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9373204.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6654776.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8822534.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6157909.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3002467.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1482055.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33931911.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-2053420.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38854050.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29576557.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35599597.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33810551.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28690652.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29913843.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13802607.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-853961.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8469674.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4488706.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987216.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329403.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7844145.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8470298.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7844150.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7844144.mp4", durationInSeconds: 2.92, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false }
  ],
  overlays: [
  { kind: "stat", value: "2.000-4.000 €", sub: "LA FACTURA MÁS TEMIDA DEL AUTOMÓVIL", fromSeconds: 17.71, durationInSeconds: 2.8 },
  { kind: "hook", text: "NINGUNA CAJA ES\n\"DE POR VIDA\"", fromSeconds: 33.42, durationInSeconds: 2.6 },
  { kind: "hook", text: "SECRETO 1\n\"DE POR VIDA\" = MENTIRA", fromSeconds: 67.12, durationInSeconds: 2.6 },
  { kind: "stat", value: "DSG: ACEITE + FILTRO", sub: "CADA 60.000 KM", fromSeconds: 100.43, durationInSeconds: 2.8 },
  { kind: "caption", text: "EL ACEITE LUBRICA + REFRIGERA + DA PRESIÓN", fromSeconds: 109.24, durationInSeconds: 2.5 },
  { kind: "caption", text: "SIN CAMBIO DE ACEITE = AVERÍA SEGURA", fromSeconds: 139.98, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 2\nCADA CAJA, SU PUNTO DÉBIL", fromSeconds: 144.94, durationInSeconds: 2.6 },
  { kind: "stat", value: "2.000-3.500 €", sub: "CAMBIAR LA MECATRÓNICA DSG", fromSeconds: 197.27, durationInSeconds: 2.8 },
  { kind: "caption", text: "DSG 7 SECA (DQ200) · EMBRAGUES EN CIUDAD", fromSeconds: 202.68, durationInSeconds: 2.5 },
  { kind: "caption", text: "DSG 6 HÚMEDA (DQ250) · MÁS ROBUSTA, EXIGE ACEITE", fromSeconds: 212.1, durationInSeconds: 2.5 },
  { kind: "stat", value: "2008-2014", sub: "MÁS CASOS DE FALLO DE MECATRÓNICA", fromSeconds: 225.17, durationInSeconds: 2.8 },
  { kind: "caption", text: "CVT: TALÓN DE AQUILES = CORREA + ACEITE", fromSeconds: 252.02, durationInSeconds: 2.5 },
  { kind: "caption", text: "CVT JATCO · DEMANDAS EN EE.UU.", fromSeconds: 258.54, durationInSeconds: 2.5 },
  { kind: "stat", value: "CVT: ACEITE", sub: "CADA 40-60.000 KM", fromSeconds: 286.36, durationInSeconds: 2.8 },
  { kind: "caption", text: "QASHQAI CVT: HASTA CADA 35-40.000 KM", fromSeconds: 301.74, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 3\nEL TIEMPO CUENTA COMO EL KM", fromSeconds: 306.21, durationInSeconds: 2.6 },
  { kind: "stat", value: "60.000 KM · O 4 AÑOS", sub: "LO QUE OCURRA ANTES", fromSeconds: 328.59, durationInSeconds: 2.8 },
  { kind: "caption", text: "EL ACEITE SE OXIDA CON LOS AÑOS, NO SOLO CON EL USO", fromSeconds: 335.22, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 4\nLA DIÁLISIS QUE CASI NADIE HACE", fromSeconds: 361.16, durationInSeconds: 2.6 },
  { kind: "stat", value: "CAMBIO NORMAL", sub: "SOLO RENUEVA 50-60%", fromSeconds: 374.74, durationInSeconds: 2.8 },
  { kind: "stat", value: "DIÁLISIS", sub: "RENUEVA 90-95%", fromSeconds: 390.2, durationInSeconds: 2.8 },
  { kind: "caption", text: "CON MUCHOS KM: PIDE DIÁLISIS, NO VACIADO", fromSeconds: 418.46, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 5\nLOS HÁBITOS QUE MATAN TU CAJA", fromSeconds: 423.97, durationInSeconds: 2.6 },
  { kind: "caption", text: "ERROR 1 · MOVER EL COCHE CON EL MOTOR APAGADO", fromSeconds: 436.78, durationInSeconds: 2.5 },
  { kind: "caption", text: "ERROR 2 · PARADO EN 'D' = CALOR Y DESGASTE", fromSeconds: 478.94, durationInSeconds: 2.5 },
  { kind: "caption", text: "ERROR 3 · EXIGIR LA CAJA EN FRÍO", fromSeconds: 487.1, durationInSeconds: 2.5 },
  { kind: "caption", text: "ERROR 4 · CAMBIAR D-R SIN PARAR DEL TODO", fromSeconds: 510.58, durationInSeconds: 2.5 },
  { kind: "caption", text: "ERROR 5 · ABUSAR DEL LAUNCH CONTROL", fromSeconds: 526.06, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 6\nEL SOFTWARE TAMBIÉN FALLA", fromSeconds: 538.01, durationInSeconds: 2.6 },
  { kind: "caption", text: "SOFTWARE VIEJO = TIRONES O MODO EMERGENCIA", fromSeconds: 559.08, durationInSeconds: 2.5 },
  { kind: "caption", text: "ANTES DE REPARAR: ACTUALIZA EL SOFTWARE", fromSeconds: 576.52, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 7\nLAS SEÑALES ANTES DE MORIR", fromSeconds: 585.28, durationInSeconds: 2.6 },
  { kind: "caption", text: "SEÑAL · TIRONES AL CAMBIAR (EN FRÍO)", fromSeconds: 596.3, durationInSeconds: 2.5 },
  { kind: "caption", text: "SEÑAL · RETRASO AL METER MARCHA ATRÁS", fromSeconds: 603.94, durationInSeconds: 2.5 },
  { kind: "caption", text: "CVT · SUBEN LAS RPM PERO NO ACELERA", fromSeconds: 635.22, durationInSeconds: 2.5 },
  { kind: "caption", text: "A TIEMPO: MUCHAS SE ARREGLAN CON ACEITE", fromSeconds: 643.5, durationInSeconds: 2.5 },
  { kind: "hook", text: "SECRETO 8\nCUÁNDO EL ACEITE YA NO SALVA", fromSeconds: 671.05, durationInSeconds: 2.6 },
  { kind: "caption", text: "EL ACEITE ES PREVENTIVO, NO CURATIVO", fromSeconds: 682.66, durationInSeconds: 2.5 },
  { kind: "caption", text: "SI YA HAY DAÑO MECÁNICO, EL ACEITE LLEGA TARDE", fromSeconds: 697.78, durationInSeconds: 2.5 },
  { kind: "caption", text: "2ª MANO QUE YA PATINA: QUE LO VALORE UN ESPECIALISTA", fromSeconds: 728.14, durationInSeconds: 2.5 },
  { kind: "hook", text: "NO FALLA POR MALA SUERTE:\nFALLA POR EL MANTENIMIENTO", fromSeconds: 770.39, durationInSeconds: 2.6 },
  { kind: "hook", text: "SUSCRÍBETE", fromSeconds: 838.38, durationInSeconds: 2.6 }
  ],
  pins: [

  ],
};
