// GENERADO por scripts/build-video.mjs — no editar a mano.
export const FPS = 30;

export type Shot = {
  clipSrc: string;
  durationInSeconds: number;
  startFromSeconds?: number;
  kenBurns?: "in" | "out" | "none";
  framed?: boolean;
  isImage?: boolean;
  sfx?: boolean;
};

export type Overlay =
  | { kind: "caption"; text: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "stat"; value: string; sub: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "hook"; text: string; fromSeconds: number; durationInSeconds: number };

export type Pin =
  | { kind: "image"; src: string; label?: string; fromSeconds: number; durationInSeconds: number }
  | { kind: "duo"; srcA: string; srcB: string; labelA: string; labelB: string; fromSeconds: number; durationInSeconds: number };

export type VideoConfig = {
  width: number; height: number; fps: number;
  narrationSrc?: string; musicSrc?: string; totalDurationInSeconds: number;
  shots: Shot[]; overlays: Overlay[]; pins: Pin[];
};

// Tipos antiguos (compatibilidad; sin uso)
export type DataGraphic =
  | { kind: "percent"; value: number; label: string }
  | { kind: "counter"; value: number; label: string; prefix?: string; suffix?: string }
  | { kind: "bars"; label: string; items: { name: string; value: number }[] };
export type Scene = {
  id: string; durationInSeconds: number; type: "clip" | "data";
  clipSrc?: string; caption?: string;
  colorGrade?: "teal-orange" | "desaturated-cold" | "warm-neutral" | "none";
  kenBurns?: "in" | "out" | "in-out" | "none";
  data?: DataGraphic;
  transitionIn?: "slide-glitch" | "whoosh" | "shutter" | "none";
};

export const videoConfig: VideoConfig = {
  width: 1920,
  height: 1080,
  fps: FPS,
  narrationSrc: "assets/audio/narration.mp3",
  musicSrc: "assets/audio/musica-fondo.mp3",
  totalDurationInSeconds: 782.63,
  shots: [
  { clipSrc: "assets/clips/v-3006972.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-1482055.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-6571483.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-38854050.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-13371634.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-34118771.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-30627892.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-3059072.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-5514359.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-20693180.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-30718439.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-7875596.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-8562464.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: true },
  { clipSrc: "assets/clips/v-11901734.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12839875.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34691446.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-27168265.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14476657.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9339075.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9318298.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14190065.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14490595.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-10937542.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35538386.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36093115.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-11663090.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32917655.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8865763.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31177452.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3111479.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-39013874.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7356356.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-27902022.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35849234.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32143671.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15075563.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38995224.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7714428.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15209900.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1315986.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6183234.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-10512333.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-1315996.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38452040.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29602834.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5418966.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9318299.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32901545.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33604722.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15330792.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15830663.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6817047.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35018126.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15775322.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-15828653.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13967042.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20589891.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30820452.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8865367.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38103675.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18849945.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38517980.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-33445783.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-10143305.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-39378296.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31799823.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38854034.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36107277.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29114133.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5982894.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8996215.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3156802.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5972218.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4632167.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3903979.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-18429902.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29927708.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14490585.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-28730389.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-17798063.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693201.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693181.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987070.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8986475.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329380.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329385.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693197.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693196.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38278795.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35555887.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8865220.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32013220.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38403669.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29902182.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16343098.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9318304.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16343407.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38341677.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-29779721.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35538387.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12901604.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9318021.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31177922.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-38046338.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-27658695.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-17555856.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13850345.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32084013.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36079508.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6312479.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12769430.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5911023.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-2229697.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-13798561.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6817046.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4337977.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6817044.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154208.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5419057.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154219.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154215.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154235.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220643.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-32329376.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220517.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8469674.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-36381466.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-8987276.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-20693191.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30010011.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220616.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220595.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220526.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-17770564.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-34539090.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35666229.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220606.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31220663.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5701516.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5419064.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16005054.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-31901297.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12839189.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-4334863.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-6900891.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-5418126.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154214.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154229.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154228.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154230.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154221.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154209.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154210.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-7154222.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-12769429.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16304650.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-3785380.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35351321.mp4", durationInSeconds: 6, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-9592753.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-35351320.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "out", framed: true, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-16653342.mp4", durationInSeconds: 5, startFromSeconds: 0, kenBurns: "in", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-30010030.mp4", durationInSeconds: 4, startFromSeconds: 0, kenBurns: "out", framed: false, isImage: false, sfx: false },
  { clipSrc: "assets/clips/v-14490728.mp4", durationInSeconds: 5.63, startFromSeconds: 0, kenBurns: "in", framed: true, isImage: false, sfx: false }
  ],
  overlays: [
  { kind: "stat", value: "85.590", sub: "CONDUCTORES REALES · OCU 2026", fromSeconds: 29.08, durationInSeconds: 2.8 },
  { kind: "hook", text: "TIER LIST SUV\nFIABILIDAD 2026", fromSeconds: 47.1, durationInSeconds: 2.6 },
  { kind: "hook", text: "TIER S\nLOS INTOCABLES", fromSeconds: 50.47, durationInSeconds: 2.6 },
  { kind: "stat", value: "TIER S", sub: "LEXUS NX / RX", fromSeconds: 66, durationInSeconds: 2.8 },
  { kind: "stat", value: "OCU 93/100", sub: "LEXUS · Nº1 FIABILIDAD 2026", fromSeconds: 76.53, durationInSeconds: 2.8 },
  { kind: "stat", value: "550 €/AÑO", sub: "MANTENIMIENTO LEXUS (vs 900 ALEMANAS)", fromSeconds: 90.75, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER S", sub: "TOYOTA RAV4 / C-HR", fromSeconds: 101, durationInSeconds: 2.8 },
  { kind: "stat", value: "OCU 96/100", sub: "TOYOTA RAV4 · HÍBRIDO HSD", fromSeconds: 113.84, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER S", sub: "SUBARU FORESTER / OUTBACK", fromSeconds: 137.1, durationInSeconds: 2.8 },
  { kind: "stat", value: "OCU 91/100", sub: "SUBARU · BOXER + AWD PERMANENTE", fromSeconds: 141.37, durationInSeconds: 2.8 },
  { kind: "hook", text: "TIER A\nMUY RECOMENDABLES", fromSeconds: 168.59, durationInSeconds: 2.6 },
  { kind: "stat", value: "TIER A", sub: "MAZDA CX-5 · 2.0 SKYACTIV ATMOSFÉRICO", fromSeconds: 183.16, durationInSeconds: 2.8 },
  { kind: "stat", value: "447 €/AÑO", sub: "MAZDA CX-5 · Nº1 RepairPal", fromSeconds: 200.14, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER A", sub: "SUZUKI VITARA / S-CROSS · BARATO DE MANTENER", fromSeconds: 217.69, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER A", sub: "HONDA CR-V e:HEV · i-MMD", fromSeconds: 246.2, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER A", sub: "KIA SPORTAGE / HYUNDAI TUCSON", fromSeconds: 271.06, durationInSeconds: 2.8 },
  { kind: "caption", text: "EVITA EL 1.6 T-GDI · MEJOR HÍBRIDO O ATMOSFÉRICO", fromSeconds: 286, durationInSeconds: 2.5 },
  { kind: "hook", text: "TIER B\nCORRECTOS", fromSeconds: 295, durationInSeconds: 2.6 },
  { kind: "stat", value: "TIER B", sub: "NISSAN QASHQAI J12 (2021+) · CORREGIDO", fromSeconds: 311.03, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER B", sub: "T-ROC / ARONA / KAMIQ · TSI EA211", fromSeconds: 333.69, durationInSeconds: 2.8 },
  { kind: "caption", text: "VW SUBE: PUESTO 31 A 25 (OCU 2026)", fromSeconds: 346.47, durationInSeconds: 2.5 },
  { kind: "stat", value: "TIER B", sub: "DACIA DUSTER · SIMPLE Y BARATO", fromSeconds: 365.92, durationInSeconds: 2.8 },
  { kind: "hook", text: "TIER C\nCON PRECAUCIÓN", fromSeconds: 383, durationInSeconds: 2.6 },
  { kind: "stat", value: "TIER C", sub: "PEUGEOT 3008 / C5 AIRCROSS · 1.2 PureTech", fromSeconds: 400.13, durationInSeconds: 2.8 },
  { kind: "stat", value: "OCU 76/100", sub: "PEUGEOT/CITROËN · POR DEBAJO DE VW", fromSeconds: 410, durationInSeconds: 2.8 },
  { kind: "caption", text: "CORREA DE DISTRIBUCIÓN EN BAÑO DE ACEITE (PureTech)", fromSeconds: 415.33, durationInSeconds: 2.5 },
  { kind: "stat", value: "TIER C", sub: "JEEP COMPASS / RENEGADE · 1.3 GSE + DCT", fromSeconds: 430.66, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER C → D", sub: "QASHQAI J11 · CVT JATCO PROBLEMÁTICA", fromSeconds: 456.32, durationInSeconds: 2.8 },
  { kind: "hook", text: "TIER D\nEVITAR SALVO GANGA", fromSeconds: 477.14, durationInSeconds: 2.6 },
  { kind: "stat", value: "TIER D", sub: "MG ZS / HS · 'LA GRAN DECEPCIÓN' OCU", fromSeconds: 488.93, durationInSeconds: 2.8 },
  { kind: "stat", value: "OCU 72/100", sub: "MG · PENÚLTIMA POSICIÓN", fromSeconds: 502.14, durationInSeconds: 2.8 },
  { kind: "stat", value: "TIER D", sub: "ALFA STELVIO / DS7 · ELÉCTRICA + DEPRECIACIÓN", fromSeconds: 521.55, durationInSeconds: 2.8 },
  { kind: "hook", text: "TIER F\nHUIR", fromSeconds: 539.21, durationInSeconds: 2.6 },
  { kind: "stat", value: "TIER F", sub: "LAND ROVER · ÚLTIMO DE LA OCU 2026", fromSeconds: 549.45, durationInSeconds: 2.8 },
  { kind: "stat", value: "OCU 64/100", sub: "LAND ROVER · FAROLILLO ROJO", fromSeconds: 557.28, durationInSeconds: 2.8 },
  { kind: "caption", text: "TRIÁNGULO DEL TERROR: NEUMÁTICA + ELECTRÓNICA + ACCESO", fromSeconds: 572, durationInSeconds: 2.5 },
  { kind: "hook", text: "EL PATRÓN:\nSIMPLE ARRIBA, COMPLEJO ABAJO", fromSeconds: 640.18, durationInSeconds: 2.6 },
  { kind: "caption", text: "MECÁNICA PROBADA > EXCESO DE ELECTRÓNICA", fromSeconds: 681.11, durationInSeconds: 2.5 },
  { kind: "caption", text: "EL MOTOR CONCRETO MUEVE 2 TIERS", fromSeconds: 706.7, durationInSeconds: 2.5 },
  { kind: "hook", text: "SUSCRÍBETE", fromSeconds: 776, durationInSeconds: 2.6 }
  ],
  pins: [
  { kind: "image", src: "assets/img/img-lexus-nx-2023-suv.jpg", label: "LEXUS NX / RX", fromSeconds: 66, durationInSeconds: 7 },
  { kind: "image", src: "assets/img/img-lexus-nx-2023-suv-1.jpg", label: "LEXUS NX / RX", fromSeconds: 73, durationInSeconds: 7 },
  { kind: "image", src: "assets/img/img-lexus-nx-2023-suv-2.jpg", label: "LEXUS NX / RX", fromSeconds: 80, durationInSeconds: 7 },
  { kind: "image", src: "assets/img/img-lexus-nx-2023-suv-3.jpg", label: "LEXUS NX / RX", fromSeconds: 87, durationInSeconds: 7 },
  { kind: "image", src: "assets/img/img-lexus-nx-2023-suv-4.jpg", label: "LEXUS NX / RX", fromSeconds: 94, durationInSeconds: 7 },
  { kind: "image", src: "assets/img/img-toyota-rav4-2023.jpg", label: "TOYOTA RAV4", fromSeconds: 101, durationInSeconds: 7.22 },
  { kind: "image", src: "assets/img/img-toyota-rav4-2023-1.jpg", label: "TOYOTA RAV4", fromSeconds: 108.22, durationInSeconds: 7.22 },
  { kind: "image", src: "assets/img/img-toyota-rav4-2023-2.jpg", label: "TOYOTA RAV4", fromSeconds: 115.44, durationInSeconds: 7.22 },
  { kind: "image", src: "assets/img/img-toyota-rav4-2023-3.jpg", label: "TOYOTA RAV4", fromSeconds: 122.66, durationInSeconds: 7.22 },
  { kind: "image", src: "assets/img/img-toyota-rav4-2023-4.jpg", label: "TOYOTA RAV4", fromSeconds: 129.88, durationInSeconds: 7.22 },
  { kind: "image", src: "assets/img/img-subaru-forester-2023.jpg", label: "SUBARU FORESTER", fromSeconds: 137.1, durationInSeconds: 7.87 },
  { kind: "image", src: "assets/img/img-subaru-forester-2023-1.jpg", label: "SUBARU FORESTER", fromSeconds: 144.97, durationInSeconds: 7.87 },
  { kind: "image", src: "assets/img/img-subaru-forester-2023-2.jpg", label: "SUBARU FORESTER", fromSeconds: 152.84, durationInSeconds: 7.87 },
  { kind: "image", src: "assets/img/img-subaru-forester-2023-3.jpg", label: "SUBARU FORESTER", fromSeconds: 160.71, durationInSeconds: 7.87 },
  { kind: "image", src: "assets/img/img-mazda-cx-5-2023.jpg", label: "MAZDA CX-5", fromSeconds: 183.16, durationInSeconds: 6.91 },
  { kind: "image", src: "assets/img/img-mazda-cx-5-2023-1.jpg", label: "MAZDA CX-5", fromSeconds: 190.07, durationInSeconds: 6.91 },
  { kind: "image", src: "assets/img/img-mazda-cx-5-2023-2.jpg", label: "MAZDA CX-5", fromSeconds: 196.97, durationInSeconds: 6.91 },
  { kind: "image", src: "assets/img/img-mazda-cx-5-2023-3.jpg", label: "MAZDA CX-5", fromSeconds: 203.88, durationInSeconds: 6.91 },
  { kind: "image", src: "assets/img/img-mazda-cx-5-2023-4.jpg", label: "MAZDA CX-5", fromSeconds: 210.79, durationInSeconds: 6.91 },
  { kind: "image", src: "assets/img/img-suzuki-vitara-2023.jpg", label: "SUZUKI VITARA", fromSeconds: 217.69, durationInSeconds: 7.13 },
  { kind: "image", src: "assets/img/img-suzuki-vitara-2023-1.jpg", label: "SUZUKI VITARA", fromSeconds: 224.82, durationInSeconds: 7.13 },
  { kind: "image", src: "assets/img/img-suzuki-vitara-2023-2.jpg", label: "SUZUKI VITARA", fromSeconds: 231.95, durationInSeconds: 7.13 },
  { kind: "image", src: "assets/img/img-suzuki-vitara-2023-3.jpg", label: "SUZUKI VITARA", fromSeconds: 239.07, durationInSeconds: 7.13 },
  { kind: "image", src: "assets/img/img-honda-cr-v-2023.jpg", label: "HONDA CR-V", fromSeconds: 246.2, durationInSeconds: 6.22 },
  { kind: "image", src: "assets/img/img-honda-cr-v-2023-1.jpg", label: "HONDA CR-V", fromSeconds: 252.42, durationInSeconds: 6.22 },
  { kind: "image", src: "assets/img/img-honda-cr-v-2023-2.jpg", label: "HONDA CR-V", fromSeconds: 258.63, durationInSeconds: 6.22 },
  { kind: "image", src: "assets/img/img-honda-cr-v-2023-3.jpg", label: "HONDA CR-V", fromSeconds: 264.85, durationInSeconds: 6.22 },
  { kind: "image", src: "assets/img/img-kia-sportage-2023.jpg", label: "KIA SPORTAGE / HYUNDAI TUCSON", fromSeconds: 271.06, durationInSeconds: 7.98 },
  { kind: "image", src: "assets/img/img-kia-sportage-2023-1.jpg", label: "KIA SPORTAGE / HYUNDAI TUCSON", fromSeconds: 279.04, durationInSeconds: 7.98 },
  { kind: "image", src: "assets/img/img-kia-sportage-2023-2.jpg", label: "KIA SPORTAGE / HYUNDAI TUCSON", fromSeconds: 287.02, durationInSeconds: 7.98 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2023.jpg", label: "NISSAN QASHQAI J12", fromSeconds: 310.18, durationInSeconds: 7.84 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2023-1.jpg", label: "NISSAN QASHQAI J12", fromSeconds: 318.02, durationInSeconds: 7.84 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2023-2.jpg", label: "NISSAN QASHQAI J12", fromSeconds: 325.86, durationInSeconds: 7.84 },
  { kind: "image", src: "assets/img/img-volkswagen-t-roc-2023.jpg", label: "VW T-ROC / ARONA / KAMIQ", fromSeconds: 333.69, durationInSeconds: 6.45 },
  { kind: "image", src: "assets/img/img-volkswagen-t-roc-2023-1.jpg", label: "VW T-ROC / ARONA / KAMIQ", fromSeconds: 340.14, durationInSeconds: 6.45 },
  { kind: "image", src: "assets/img/img-volkswagen-t-roc-2023-2.jpg", label: "VW T-ROC / ARONA / KAMIQ", fromSeconds: 346.58, durationInSeconds: 6.45 },
  { kind: "image", src: "assets/img/img-volkswagen-t-roc-2023-3.jpg", label: "VW T-ROC / ARONA / KAMIQ", fromSeconds: 353.03, durationInSeconds: 6.45 },
  { kind: "image", src: "assets/img/img-volkswagen-t-roc-2023-4.jpg", label: "VW T-ROC / ARONA / KAMIQ", fromSeconds: 359.48, durationInSeconds: 6.45 },
  { kind: "image", src: "assets/img/img-dacia-duster-2023.jpg", label: "DACIA DUSTER", fromSeconds: 365.92, durationInSeconds: 8.54 },
  { kind: "image", src: "assets/img/img-dacia-duster-2023-1.jpg", label: "DACIA DUSTER", fromSeconds: 374.46, durationInSeconds: 8.54 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2023.jpg", label: "PEUGEOT 3008 / C5 AIRCROSS", fromSeconds: 400.13, durationInSeconds: 7.63 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2023-1.jpg", label: "PEUGEOT 3008 / C5 AIRCROSS", fromSeconds: 407.76, durationInSeconds: 7.63 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2023-2.jpg", label: "PEUGEOT 3008 / C5 AIRCROSS", fromSeconds: 415.4, durationInSeconds: 7.63 },
  { kind: "image", src: "assets/img/img-peugeot-3008-2023-3.jpg", label: "PEUGEOT 3008 / C5 AIRCROSS", fromSeconds: 423.03, durationInSeconds: 7.63 },
  { kind: "image", src: "assets/img/img-jeep-compass-2023.jpg", label: "JEEP COMPASS / RENEGADE", fromSeconds: 430.66, durationInSeconds: 6.42 },
  { kind: "image", src: "assets/img/img-jeep-compass-2023-1.jpg", label: "JEEP COMPASS / RENEGADE", fromSeconds: 437.07, durationInSeconds: 6.42 },
  { kind: "image", src: "assets/img/img-jeep-compass-2023-2.jpg", label: "JEEP COMPASS / RENEGADE", fromSeconds: 443.49, durationInSeconds: 6.42 },
  { kind: "image", src: "assets/img/img-jeep-compass-2023-3.jpg", label: "JEEP COMPASS / RENEGADE", fromSeconds: 449.9, durationInSeconds: 6.42 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2016.jpg", label: "NISSAN QASHQAI J11", fromSeconds: 456.32, durationInSeconds: 6.94 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2016-1.jpg", label: "NISSAN QASHQAI J11", fromSeconds: 463.26, durationInSeconds: 6.94 },
  { kind: "image", src: "assets/img/img-nissan-qashqai-2016-2.jpg", label: "NISSAN QASHQAI J11", fromSeconds: 470.2, durationInSeconds: 6.94 },
  { kind: "image", src: "assets/img/img-mg-zs-suv-2023.jpg", label: "MG ZS / HS", fromSeconds: 488.93, durationInSeconds: 6.52 },
  { kind: "image", src: "assets/img/img-mg-zs-suv-2023-1.jpg", label: "MG ZS / HS", fromSeconds: 495.45, durationInSeconds: 6.52 },
  { kind: "image", src: "assets/img/img-mg-zs-suv-2023-2.jpg", label: "MG ZS / HS", fromSeconds: 501.98, durationInSeconds: 6.52 },
  { kind: "image", src: "assets/img/img-mg-zs-suv-2023-3.jpg", label: "MG ZS / HS", fromSeconds: 508.5, durationInSeconds: 6.52 },
  { kind: "image", src: "assets/img/img-mg-zs-suv-2023-4.jpg", label: "MG ZS / HS", fromSeconds: 515.03, durationInSeconds: 6.52 },
  { kind: "image", src: "assets/img/img-alfa-romeo-stelvio-2023.jpg", label: "ALFA STELVIO / DS7", fromSeconds: 521.55, durationInSeconds: 5.89 },
  { kind: "image", src: "assets/img/img-alfa-romeo-stelvio-2023-1.jpg", label: "ALFA STELVIO / DS7", fromSeconds: 527.44, durationInSeconds: 5.89 },
  { kind: "image", src: "assets/img/img-alfa-romeo-stelvio-2023-2.jpg", label: "ALFA STELVIO / DS7", fromSeconds: 533.32, durationInSeconds: 5.89 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2023.jpg", label: "LAND ROVER", fromSeconds: 549.45, durationInSeconds: 7.31 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2023-1.jpg", label: "LAND ROVER", fromSeconds: 556.76, durationInSeconds: 7.31 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2023-2.jpg", label: "LAND ROVER", fromSeconds: 564.07, durationInSeconds: 7.31 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2023-3.jpg", label: "LAND ROVER", fromSeconds: 571.38, durationInSeconds: 7.31 },
  { kind: "image", src: "assets/img/img-range-rover-evoque-2023-4.jpg", label: "LAND ROVER", fromSeconds: 578.69, durationInSeconds: 7.31 }
  ],
};
